---
title: "Recruitment"
format: html
execute: 
  echo: false  
---

```{r setup}
#| label: load-packages
#| include: false

library(ggokabeito)
library(ggplot2)
library(tidyverse)
library(lubridate)

# Create custom palette based on Okabe-Ito but with specified first colors
custom_palette <- c("#068194", "#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


options(
  # set default colors in ggplot2 to colorblind-friendly
  # Okabe-Ito and Viridis palettes
  ggplot2.discrete.colour = custom_palette,
  ggplot2.discrete.fill = custom_palette,
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  # set theme font and size
  book.base_family = "sans",
  book.base_size = 14
)

# set default theme
theme_set(
  theme_minimal(
    base_size = getOption("book.base_size"),
    base_family = getOption("book.base_family")
  ) %+replace%
    theme(
      panel.grid.minor = element_blank(),
      legend.position = "bottom"
    )
)
```

```{r fig-1}
#| echo: true
#| fig-cap: "Recruitment"
#| fig-width: 10
#| fig-height: 6

file_info <- file.info("data/recruitment_data.csv")
recruitment_data <- read.csv("data/recruitment_data.csv")

random_data <- recruitment_data |> 
  select(random_date) |> 
  mutate(random_date = as_date(random_date))  |> 
  arrange(random_date) |> 
  mutate(n = row_number(),
         group = "Random selection for invitation to the trial") #random selection

uptake_data <- recruitment_data  |> 
  mutate(icf_date = as_date(icddate)) |> 
  filter(!is.na(icf_date) & icf_reg == 1)  |> 
  select(icf_date) |> 
  arrange(icf_date) |> 
  mutate(n = row_number(),
         group = "Informed consent signed")

plot <- ggplot() +
  #graphing random selection
  geom_point(data = random_data, aes(x = random_date, y = n, color = group)) +
  geom_line(data = random_data, aes(x = random_date, y = n, color = group)) +
  geom_area(data = random_data, aes(x = random_date, y = n, fill = group), alpha = 0.1) +
  #graphing uptake
  geom_point(data = uptake_data, aes(x = icf_date, y = n, color = group)) +
  geom_line(data = uptake_data, aes(x = icf_date, y = n, color = group)) +
  geom_area(data = uptake_data, aes(x = icf_date, y = n, fill = group), alpha = 0.5) +
  geom_hline(yintercept = 150, linetype = "solid", color = custom_palette[1], linewidth = 1) +
  #style
  scale_x_date(date_breaks = "3 months", date_labels =  "%b %Y", limits = c(as.Date("2024-04-29"), as.Date("2025-10-31"))) +
  scale_y_continuous(limits = c(0, 160), 
                    breaks = c(0, 50, 100, 150),  # All the labels we want
                    minor_breaks = seq(0, 150, 25),  # Minor gridlines stopping at 140
                    labels = c("0", "50", "100", "150")) +
  ylab("number of patients") +
  xlab("") +
  guides(color = guide_legend(title = NULL), fill = guide_legend(title = NULL)) +
  annotate("rect", 
           xmin = as.Date("2024-05-30"), xmax = as.Date("2024-12-01"),  # Adjust these dates
           ymin = 145, ymax = 155,  # Adjust these values to fit your text
           fill = "white") +
  annotate("text", x = as.Date("2024-08-30"), 
           y = 150, label = "target of consented patients", 
           color = custom_palette[1], size = 5, 
           hjust = 0.5, vjust = 0.3) +
  theme(
    panel.grid.minor.y = element_line(color = "gray95"),
    panel.grid.major.y = element_line(color = "gray80")
  )

plot
```

Eligible patients at the Division of Medical Oncology at the University Hospital Basel are randomly invited to participate in the LIQPLAT trial. We aim to recruit 150 participants within 18 months. As of `r as.Date(file_info$ctime)`, `r nrow(uptake_data)` patients have agreed to participate in the trial.
